name: Terraform Destroy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  scan:
    uses: guilherme-aroliveira/gh-workflows/.github/workflows/scan.yaml@main

  ci:
    needs: scan
    uses: guilherme-aroliveira/gh-workflows/.github/workflows/tf-destroy.yaml@main
    with:
      working_directory: './cloud-infrastructure/environments/dev/'
      tf_version: '1.10.5'
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      #access_role: ${{ secrets.ACCESS_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
      AWS_DYNAMODB_TABLE: ${{ secrets.AWS_DYNAMODB_TABLE }}