name: Terraform Destroy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  scan:
    uses: guilherme-aroliveira/gh-workflows/.github/workflows/scan.yaml@main

  lint:
    needs: scan
    uses: guilherme-aroliveira/gh-workflows/.github/workflows/tf-lint.yaml@main
    with:
      working_directory: './cloud-infrastructure/environments/dev/'
      tf_version: '1.10.5'
  
  #plan:
  #  needs: lint
  #  uses: guilherme-aroliveira/gh-workflows/.github/workflows/tf-plan.yaml@main
  #  with:
  #    working_directory: './cloud-infrastructure/environments/dev/'
  #    tf_version: '1.10.5'
  #  secrets: 
  #    ASSUME_ROLE: ${{ secrets.ASSUME_ROLE }}
  #    AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  #    AWS_BUCKET_KEY: ${{ secrets.AWS_BUCKET_KEY_NAME }}
  #    AWS_DYNAMODB_TABLE: ${{ secrets.AWS_DYNAMODB_TABLE }}
  #    AWS_REGION: ${{ secrets.AWS_REGION }}

